package com.interview.agent.model;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a User entity in the database.
 * This class is mapped to the "users" table.
 */
@Entity
@Table(name = "users")
@Data
public class User {

    /**
     * The unique identifier for the user.
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full name of the user.
     * This field cannot be null.
     */
    @Column(nullable = false)
    private String fullName;

    /**
     * The email address of the user, used for login and identification.
     * This field must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The user's password, stored in a hashed format.
     * This field cannot be null.
     */
    @Column(nullable = false)
    private String password;

    /**
     * The timestamp when the user account was created.
     * This is automatically set by Hibernate upon creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(updatable = false, nullable = false)
    private LocalDateTime createdAt;
}